project:
  type: website
  output-dir: docs

website:
  title: "Creaci贸n de reportes en Quarto y R"
  image: icon.png
  favicon: icon.png
  open-graph: true
  navbar:
    logo: icon.png
    title: false
    left:
      - href: index.qmd
        text: Inicio
      - materiales.qmd
      - trabajo.qmd
      - text: M贸dulos
        menu:
          - text: "M贸dulo 1"
            href: "https://mmorenozam.github.io/see-quarto-modulo1/"
          - text: "M贸dulo 2"
            href: "https://mmorenozam.github.io/see-quarto-modulo2/"


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-location: left
    toc-title: Contenido
